name: Run SonarQube with Docker Compose

on: 
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: sonarqube scan
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false

    - name: Run Docker Compose
      run: docker-compose up -d
