name: Run SonarQube Analysis

on: push

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Pull and run SonarQube container
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
          # Wait for SonarQube to be fully operational
          until curl -s http://localhost:9000 > /dev/null; do sleep 5; done

      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: "http://localhost:9000"
          SONAR_LOGIN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          sonar-scanner -Dsonar.projectKey=tictactoe_react_proto -Dsonar.sources=./src
