- name: Set up WireGuard
  uses: egor-tensin/setup-wireguard@v1
  with:
    endpoint: '${{ secrets.ENDPOINT }}'
    endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
    ips: '${{ secrets.IPS }}'
    allowed_ips: '${{ secrets.ALLOWED_IPS }}'
    private_key: '${{ secrets.PRIVATE }}'
    preshared_key: '${{ secrets.PRESHARED }}'
